<?php

/**
 * This is the model base class for the table "supporter".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Supporter".
 *
 * Columns in table "supporter" available as properties of the model,
 * followed by relations of table "supporter" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $fundraiser_id
 * @property integer $relation_id
 * @property string $supporter_message
 * @property string $created_date
 * @property string $updated_date
 * @property string $status
 *
 * @property SetupFundraiser $fundraiser
 * @property Relationship $relation
 * @property Users $user
 */
abstract class BaseSupporter extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'supporter';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Supporter|Supporters', $n);
	}

	public static function representingColumn() {
		return 'supporter_message';
	}

	public function rules() {
		return array(
			array('user_id, fundraiser_id, relation_id, supporter_message, created_date', 'required'),
			array('user_id, fundraiser_id, relation_id', 'numerical', 'integerOnly'=>true),
			array('status', 'length', 'max'=>1),
			array('updated_date', 'safe'),
			array('updated_date, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, fundraiser_id, relation_id, supporter_message, created_date, updated_date, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fundraiser' => array(self::BELONGS_TO, 'SetupFundraiser', 'fundraiser_id'),
			'relation' => array(self::BELONGS_TO, 'Relationship', 'relation_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'fundraiser_id' => null,
			'relation_id' => null,
			'supporter_message' => Yii::t('app', 'Supporter Message'),
			'created_date' => Yii::t('app', 'Created Date'),
			'updated_date' => Yii::t('app', 'Updated Date'),
			'status' => Yii::t('app', 'Status'),
			'fundraiser' => null,
			'relation' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('fundraiser_id', $this->fundraiser_id);
		$criteria->compare('relation_id', $this->relation_id);
		$criteria->compare('supporter_message', $this->supporter_message, true);
		$criteria->compare('created_date', $this->created_date, true);
		$criteria->compare('updated_date', $this->updated_date, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}