<?php

/**
 * This is the model base class for the table "Testimonial".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Testimonial".
 *
 * Columns in table "Testimonial" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $testimonial_text
 * @property string $testimonial_by
 * @property string $testimonial_picture
 * @property string $testimonial_company
 * @property string $created_date
 * @property string $updated_date
 * @property string $status
 *
 */
abstract class BaseTestimonial extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'testimonial';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Testimonial|Testimonials', $n);
	}

	public static function representingColumn() {
		return 'testimonial_by';
	}

	public function rules() {
		return array(
			array('testimonial_by, testimonial_picture, testimonial_company, created_date, status', 'required'),
			array('testimonial_text', 'length', 'max'=>455),
			array('testimonial_by, testimonial_picture, testimonial_company', 'length', 'max'=>45),
			array('status', 'length', 'max'=>1),
			array('updated_date', 'safe'),
			array('testimonial_text, updated_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, testimonial_text, testimonial_by, testimonial_picture, testimonial_company, created_date, updated_date, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'testimonial_text' => Yii::t('app', 'Testimonial Text'),
			'testimonial_by' => Yii::t('app', 'Testimonial By'),
			'testimonial_picture' => Yii::t('app', 'Testimonial Picture'),
			'testimonial_company' => Yii::t('app', 'Testimonial Company'),
			'created_date' => Yii::t('app', 'Created Date'),
			'updated_date' => Yii::t('app', 'Updated Date'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('testimonial_text', $this->testimonial_text, true);
		$criteria->compare('testimonial_by', $this->testimonial_by, true);
		$criteria->compare('testimonial_picture', $this->testimonial_picture, true);
		$criteria->compare('testimonial_company', $this->testimonial_company, true);
		$criteria->compare('created_date', $this->created_date, true);
		$criteria->compare('updated_date', $this->updated_date, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}