<?php

/**
 * This is the model base class for the table "email_templates".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmailTemplates".
 *
 * Columns in table "email_templates" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $short_code
 * @property string $subject
 * @property string $template
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 *
 */
abstract class BaseEmailTemplates extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'email_templates';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmailTemplates|EmailTemplates', $n);
	}

	public static function representingColumn() {
		return 'short_code';
	}

	public function rules() {
		return array(
			array('short_code, subject, template, created_at', 'required'),
			array('short_code, subject', 'length', 'max'=>250),
			array('status', 'length', 'max'=>1),
			array('updated_at,text_email', 'safe'),
			array('updated_at, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, short_code, subject, template, created_at, updated_at, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'short_code' => Yii::t('app', 'Short Code'),
			'subject' => Yii::t('app', 'Subject'),
			'template' => Yii::t('app', 'Template'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('short_code', $this->short_code, true);
		$criteria->compare('subject', $this->subject, true);
		$criteria->compare('template', $this->template, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}