<?php

/**
 * This is the model base class for the table "report_fundraiser".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReportFundraiser".
 *
 * Columns in table "report_fundraiser" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $fundraiser_id
 * @property string $user_name
 * @property string $email
 * @property string $description
 * @property string $created_date
 * @property string $updated_date
 * @property string $status
 *
 */
abstract class BaseReportFundraiser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'report_fundraiser';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ReportFundraiser|ReportFundraisers', $n);
	}

	public static function representingColumn() {
		return 'user_name';
	}

	public function rules() {
		return array(
			array('fundraiser_id, user_name, email, description, created_date', 'required'),
			array('fundraiser_id', 'numerical', 'integerOnly'=>true),
			array('user_name, email, description', 'length', 'max'=>250),
			array('status', 'length', 'max'=>1),
			array('updated_date', 'safe'),
			array('updated_date, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, fundraiser_id, user_name, email, description, created_date, updated_date, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'fundraiser_id' => Yii::t('app', 'Fundraiser'),
			'user_name' => Yii::t('app', 'User Name'),
			'email' => Yii::t('app', 'Email'),
			'description' => Yii::t('app', 'Description'),
			'created_date' => Yii::t('app', 'Created Date'),
			'updated_date' => Yii::t('app', 'Updated Date'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('fundraiser_id', $this->fundraiser_id);
		$criteria->compare('user_name', $this->user_name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('created_date', $this->created_date, true);
		$criteria->compare('updated_date', $this->updated_date, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}