<?php

/**
 * This is the model base class for the table "system_actions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SystemActions".
 *
 * Columns in table "system_actions" available as properties of the model,
 * followed by relations of table "system_actions" available as properties of the model.
 *
 * @property integer $id
 * @property integer $controller_id
 * @property string $action_name
 * @property string $status
 *
 * @property SystemControllers $controller
 * @property SystemRoleBasePermission[] $systemRoleBasePermissions
 */
abstract class BaseSystemActions extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'system_actions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SystemActions|SystemActions', $n);
	}

	public static function representingColumn() {
		return 'action_name';
	}

	public function rules() {
		return array(
			array('controller_id, action_name', 'required'),
			array('controller_id', 'numerical', 'integerOnly'=>true),
			array('action_name', 'length', 'max'=>250),
			array('status', 'length', 'max'=>1),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, controller_id, action_name, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'controller' => array(self::BELONGS_TO, 'SystemControllers', 'controller_id'),
			'systemRoleBasePermissions' => array(self::HAS_MANY, 'SystemRoleBasePermission', 'action_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'controller_id' => null,
			'action_name' => Yii::t('app', 'Action Name'),
			'status' => Yii::t('app', 'Status'),
			'controller' => null,
			'systemRoleBasePermissions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('controller_id', $this->controller_id);
		$criteria->compare('action_name', $this->action_name, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}