<?php

/**
 * This is the model base class for the table "home_slider".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HomeSlider".
 *
 * Columns in table "home_slider" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $slider_title
 * @property string $slider_content
 * @property string $slider_image
 * @property string $created_date
 * @property string $updated_date
 * @property string $status
 *
 */
abstract class BaseHomeSlider extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'home_slider';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HomeSlider|HomeSliders', $n);
	}

	public static function representingColumn() {
		return 'slider_title';
	}

	public function rules() {
		return array(
			array('slider_title, slider_content, slider_image, created_date, status', 'required'),
			array('slider_title, slider_content, slider_image', 'length', 'max'=>255),
			array('status', 'length', 'max'=>1),
			array('updated_date', 'safe'),
			array('updated_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, slider_title, slider_content, slider_image, created_date, updated_date, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'slider_title' => Yii::t('app', 'Slider Title'),
			'slider_content' => Yii::t('app', 'Slider Content'),
			'slider_image' => Yii::t('app', 'Slider Image'),
			'created_date' => Yii::t('app', 'Created Date'),
			'updated_date' => Yii::t('app', 'Updated Date'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('slider_title', $this->slider_title, true);
		$criteria->compare('slider_content', $this->slider_content, true);
		$criteria->compare('slider_image', $this->slider_image, true);
		$criteria->compare('created_date', $this->created_date, true);
		$criteria->compare('updated_date', $this->updated_date, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}