<?php

/**
 * This is the model base class for the table "user_device_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserDeviceInfo".
 *
 * Columns in table "user_device_info" available as properties of the model,
 * followed by relations of table "user_device_info" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $device_token
 * @property string $device_type
 * @property string $created_date
 * @property string $updated_date
 * @property string $status
 *
 * @property Users $user
 */
abstract class BaseUserDeviceInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_device_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserDeviceInfo|UserDeviceInfos', $n);
	}

	public static function representingColumn() {
		return 'device_token';
	}

	public function rules() {
		return array(
			array('user_id, device_token, device_type, created_date', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('device_token, device_type', 'length', 'max'=>250),
			array('status', 'length', 'max'=>1),
			array('updated_date', 'safe'),
			array('updated_date, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, device_token, device_type, created_date, updated_date, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'device_token' => Yii::t('app', 'Device Token'),
			'device_type' => Yii::t('app', 'Device Type'),
			'created_date' => Yii::t('app', 'Created Date'),
			'updated_date' => Yii::t('app', 'Updated Date'),
			'status' => Yii::t('app', 'Status'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('device_token', $this->device_token, true);
		$criteria->compare('device_type', $this->device_type, true);
		$criteria->compare('created_date', $this->created_date, true);
		$criteria->compare('updated_date', $this->updated_date, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}