<?php

/**
 * This is the model base class for the table "notifications".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Notifications".
 *
 * Columns in table "notifications" available as properties of the model,
 * followed by relations of table "notifications" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $message
 * @property integer $from_id
 * @property string $from_admin
 * @property integer $to_id
 * @property string $to_admin
 * @property string $is_read
 * @property string $created_date
 * @property string $updated_date
 * @property string $status
 *
 * @property NotificationsComment[] $notificationsComments
 */
abstract class BaseNotifications extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'notifications';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Notifications|Notifications', $n);
	}

	public static function representingColumn() {
		return 'message';
	}

	public function rules() {
		return array(
			array('message, subject, fundraiser_id', 'required'),
			array('receiver_type, receiver_name', 'required', 'message' => 'Please select {attribute}'),
			array('from_id, to_id', 'numerical', 'message' => 'Please select {attribute}'),
			array('fundraiser_id', 'numerical', 'message' => 'Please select Fundraiser'),
			array('name, email', 'length', 'max'=>250),
			array('from_admin, to_admin, is_read, status', 'length', 'max'=>1),
			array('created_date, updated_date', 'safe'),
			array('name, email, from_id, from_admin, to_id, to_admin, is_read, created_date, updated_date, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, email, message, from_id, from_admin, to_id, to_admin, is_read, created_date, updated_date, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'notificationsComments' => array(self::HAS_MANY, 'NotificationsComment', 'notification_id'),
			'fromUser' => array(self::BELONGS_TO, 'Users', 'from_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'email' => Yii::t('app', 'Email'),
			'message' => Yii::t('app', 'Message'),
			'from_id' => Yii::t('app', 'From'),
			'from_admin' => Yii::t('app', 'From Admin'),
			'to_id' => Yii::t('app', 'To'),
			'to_admin' => Yii::t('app', 'To Admin'),
			'is_read' => Yii::t('app', 'Is Read'),
			'created_date' => Yii::t('app', 'Created Date'),
			'updated_date' => Yii::t('app', 'Updated Date'),
			'status' => Yii::t('app', 'Status'),
			'notificationsComments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('from_id', $this->from_id);
		$criteria->compare('from_admin', $this->from_admin, true);
		$criteria->compare('to_id', $this->to_id);
		$criteria->compare('to_admin', $this->to_admin, true);
		$criteria->compare('is_read', $this->is_read, true);
		$criteria->compare('created_date', $this->created_date, true);
		$criteria->compare('updated_date', $this->updated_date, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}