<?php

/**
 * This is the model base class for the table "donations".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Donations".
 *
 * Columns in table "donations" available as properties of the model,
 * followed by relations of table "donations" available as properties of the model.
 *
 * @property integer $id
 * @property integer $fundraiser_id
 * @property double $donation_amount
 * @property string $donor_name
 * @property string $donor_email
 * @property string $donor_phone_no
 * @property string $donor_message
 * @property integer $user_id
 * @property string $created_date
 * @property string $updated_date
 * @property string $status
 *
 * @property SetupFundraiser $fundraiser
 */
abstract class BaseDonations extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'donations';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Donations|Donations', $n);
	}

	public static function representingColumn() {
		return 'donor_name';
	}

	public function rules() {
		return array(
			array('fundraiser_id, donation_amount, donor_name, donor_email, donor_phone_no, donor_message, user_id, created_date', 'required'),
			array('fundraiser_id, user_id', 'numerical', 'integerOnly'=>true),
			array('donation_amount', 'numerical'),
			array('donor_name, donor_email, donor_phone_no', 'length', 'max'=>255),
			array('status', 'length', 'max'=>1),
			array('updated_date', 'safe'),
			array('updated_date, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, fundraiser_id, donation_amount, donor_name, donor_email, donor_phone_no, donor_message, user_id, created_date, updated_date, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fundraiser' => array(self::BELONGS_TO, 'SetupFundraiser', 'fundraiser_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'fundraiser_id' => null,
			'donation_amount' => Yii::t('app', 'Donation Amount'),
			'donor_name' => Yii::t('app', 'Donor Name'),
			'donor_email' => Yii::t('app', 'Donor Email'),
			'donor_phone_no' => Yii::t('app', 'Donor Phone No'),
			'donor_message' => Yii::t('app', 'Donor Message'),
			'user_id' => Yii::t('app', 'User'),
			'created_date' => Yii::t('app', 'Created Date'),
			'updated_date' => Yii::t('app', 'Updated Date'),
			'status' => Yii::t('app', 'Status'),
			'fundraiser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('fundraiser_id', $this->fundraiser_id);
		$criteria->compare('donation_amount', $this->donation_amount);
		$criteria->compare('donor_name', $this->donor_name, true);
		$criteria->compare('donor_email', $this->donor_email, true);
		$criteria->compare('donor_phone_no', $this->donor_phone_no, true);
		$criteria->compare('donor_message', $this->donor_message, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('created_date', $this->created_date, true);
		$criteria->compare('updated_date', $this->updated_date, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}